# Generated by Django 2.2.24 on 2021-12-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('tipo', models.CharField(choices=[('ORDINARIA', 'ORDINARIA'), ('REPITE', 'REPITE'), ('ESPECIAL', 'ESPECIAL')], default='available', max_length=45)),
                ('carrera', models.CharField(max_length=25)),
            ],
        ),
        migrations.RenameModel(
            old_name='persona',
            new_name='alumno',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='fk_persona',
            new_name='fk_alumno',
        ),
    ]
