# Generated by Django 2.2.24 on 2021-12-06 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211206_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='fk_docente',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.docente'),
            preserve_default=False,
        ),
    ]
