# Generated by Django 2.2.24 on 2021-12-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211206_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='tipo',
        ),
        migrations.AddField(
            model_name='materia',
            name='nombre',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
